### ISSUE TITLE
[Bug] Orientation Marker Tool Not Displaying Correctly in Viewport

### ISSUE THREAD

**Issue by 12otherWays** [cornerstonejs/cornerstone3D#2253]
### Describe the Bug

In the viewports, the orientation marker tool appears incorrectly, it shows multiple instances of the orientation marker instead of just one.

### Steps to Reproduce

Open multiple tabs on the browser with the viewer .

### The current behavior

Multiple orientation markers are displayed simultaneously in the same viewport, which causes visual confusion .

<img width="1440" height="769" alt="Image" src="https://github.com/user-attachments/assets/3e678070-0f22-463c-9853-fd2a97bdded4" />

### The expected behavior

Only a single orientation marker should be displayed in the viewport. It should accurately represent anatomical directions to help understand the current camera orientation.

<img width="1440" height="769" alt="Image" src="https://github.com/user-attachments/assets/083440b3-24e9-4225-a6e8-d3e8b7c318d4" />

### OS

macOS M1

### Node version

n/a

### Browser

Brave 1.80.122

**Comment by sedghi** [comment]
Hmm, can you provide a reproducible example code? Which versino of cs3d are you using

CC @IbrahimCSAE

**Comment by daker** [comment]
i believe this is an issue with the example only, if you try to switch to "custom" while it's loading data, you will get two markers

https://www.cornerstonejs.org/live-examples/orientationmarker

**Comment by IbrahimCSAE** [comment]
I thought I fixed this, is this happening on latest?

**Comment by 12otherWays** [comment]
Thanks for the responses!

- I tested this on the CornerstoneJS live [example](https://www.cornerstonejs.org/live-examples/orientationmarker), and I can reproduce the issue there.
- If I open multiple tabs of the viewer, the issue becomes more consistent, and I often see duplicate orientation markers.
- Specifically, when switching to "custom" even after the data has fully loaded I still see multiple orientation markers appear in some tabs (not every time, but intermittently).

**Comment by sedghi** [comment]
We will look thanks
